services:
  postgres:
    image: postgres:16
    mem_limit: 512m
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tls_blog
    ports:
      - "5432:5432"
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tls_blog"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - pg_data_local:/var/lib/postgresql/data
    command: >
      bash -c "docker-entrypoint.sh postgres && psql -U postgres -d tls_blog -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm;'"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  prisma-network:

volumes:
  pg_data_local:
