name: Auto Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: worker-deploy-production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source ~/.nvm/nvm.sh
            nvm use default
            cd /var/www/tls-blog
            echo $PATH
            node -v
            git pull origin main
            systemctl stop tls-blog
            pnpm i & docker compose up -d & wait
            pnpx prisma migrate deploy
            pnpx prisma generate
            pnpx prisma db seed
            pnpm build
            systemctl start tls-blog
